CREATE TABLE USER_PROFILE(
    userProfileType VARCHAR (30) NOT NULL,
    CONSTRAINT USER_PROFILE_PKEY PRIMARY KEY(userProfileType)
);

CREATE TABLE USER_ACCOUNT(
    userID VARCHAR (30) NOT NULL,
    userName VARCHAR (30) NOT NULL,
    userPassword VARCHAR (30) NOT NULL,
    userEmail VARCHAR (30) NOT NULL,
    userProfile VARCHAR (30) NOT NULL,
    userLoyalty_Pts INT (11) NOT NULL,
    CONSTRAINT USER_ACCOUNT_PKEY PRIMARY KEY(userID),
    CONSTRAINT USER_ACCOUNT_CKEY UNIQUE(userName),
    CONSTRAINT USER_ACCOUNT_FKEY FOREIGN KEY(userProfile) REFERENCES USER_PROFILE(userProfileType)
);

CREATE TABLE MOVIE(
    movieID VARCHAR (30) NOT NULL,
    movieName VARCHAR (999) NOT NULL,
    movieDescription VARCHAR (9999) NOT NULL,
    movieAvailability BOOLEAN NOT NULL,
    CONSTRAINT MOVIE_PKEY PRIMARY KEY(movieID),
    CONSTRAINT MOVIE_CKEY UNIQUE(movieName)
);

CREATE TABLE CINEMA_ROOM(
    cinema_rm_ID VARCHAR (30) NOT NULL,
    cinema_seat_list VARCHAR (100) NOT NULL,
    cinema_screening BOOLEAN NOT NULL,
    cinema_time_slot BOOLEAN NOT NULL,
    CONSTRAINT CINEMA_ROOM_PKEY PRIMARY KEY(cinema_rm_ID)
);

CREATE TABLE CINEMA_SEAT(
    seatID VARCHAR (30) NOT NULL,
    seatAvailability BOOLEAN NOT NULL,
    cinema_rm_ID VARCHAR (30) NOT NULL,
    CONSTRAINT CINEMA_SEAT_PKEY PRIMARY KEY(seatID),
    CONSTRAINT CINEMA_SEAT_FKEY FOREIGN KEY(cinema_rm_ID) REFERENCES CINEMA_ROOM(cinema_rm_ID)
);

CREATE TABLE TICKET(
    ticketID VARCHAR (30) NOT NULL,
    ticketType VARCHAR (30) NOT NULL,
    loyalty_pts INT(11) NOT NULL,
    ticket_price DECIMAL (20,4) NOT NULL,
    CONSTRAINT TICKET_PKEY PRIMARY KEY(ticketID),
    CONSTRAINT TICKET_CKEY UNIQUE(ticketType)
);

CREATE TABLE FNB(
    fnbID VARCHAR (30) NOT NULL,
    fnbName VARCHAR (999) NOT NULL,
    fnb_availability BOOLEAN NOT NULL,
    fnb_loyalty_pt INT(11) NOT NULL,
    fnb_price DECIMAL (20,4) NOT NULL,
    CONSTRAINT FNB_PKEY PRIMARY KEY(fnbID),
    CONSTRAINT FNB_CKEY UNIQUE(fnbName)
);

CREATE TABLE BOOK_TICKET(
    book_ticketID VARCHAR (30) NOT NULL,
    no_of_ticket_booked INT(11) NOT NULL,
    movie_name_booked VARCHAR (999) NOT NULL,
    ticket_type VARCHAR (30) NOT NULL,
    movie_ID VARCHAR (30) NOT NULL,
    movie_screening_date VARCHAR (30) NOT NULL,
    movie_screening_time VARCHAR (30) NOT NULL,
    cinema_rm_ID VARCHAR (30) NOT NULL,
    seatID VARCHAR (30) NOT NULL,
    CONSTRAINT BOOK_TICKET_PKEY PRIMARY KEY(book_ticketID),
    CONSTRAINT BOOK_TICKET_FKEY FOREIGN KEY(ticket_type) REFERENCES TICKET(ticketType),
    CONSTRAINT BOOK_TICKET_FKEY2 FOREIGN KEY(movie_ID) REFERENCES MOVIE(movieID),
    CONSTRAINT BOOK_TICKET_FKEY3 FOREIGN KEY(cinema_rm_ID) REFERENCES CINEMA_ROOM(cinema_rm_ID),
    CONSTRAINT BOOK_TICKET_FKEY4 FOREIGN KEY(seatID) REFERENCES CINEMA_SEAT(seatID)
);

CREATE TABLE BOOK_FNB(
    book_fbID VARCHAR (30) NOT NULL,
    fbName VARCHAR (999) NOT NULL,
    fbCost DECIMAL (20,4) NOT NULL,
    fbLoyalty_Pts INT(11) NOT NULL,
    CONSTRAINT BOOK_FNB_PKEY PRIMARY KEY(book_fbID),
    CONSTRAINT BOOK_FNB_CKEY UNIQUE (fbName)
);

CREATE TABLE PURCHASE(
    purchaseID VARCHAR (30) NOT NULL,
    book_ticketID VARCHAR (30) NOT NULL,
    book_fbID VARCHAR (30) NOT NULL,
    CONSTRAINT PURCHASE_PKEY PRIMARY KEY(purchaseID),
    CONSTRAINT PURCHASE_FKEY FOREIGN KEY(book_ticketID) REFERENCES BOOK_TICKET(book_ticketID),
    CONSTRAINT PURCHASE_FKEY2 FOREIGN KEY(book_fbID) REFERENCES BOOK_FNB(book_fbID)
);
